### ISSUE TITLE
Error: not a valid path: "got"

### ISSUE THREAD

**Issue by kdhttps** [iambumblehead/esmock#46]
## Details 

Facing error only when I tried to mock [got](https://www.npmjs.com/package/got)

```
Error: not a valid path: "got" (used by ./index.test.js)
      at esmockModulesCreate (file:///home/node-test/node_modules/esmock/src/esmockModule.js:126:11)
      at esmockModulesCreate (file:///home/node-test/node_modules/esmock/src/esmockModule.js:139:10)
      at async esmockModuleMock (file:///home/node-test/node_modules/esmock/src/esmockModule.js:146:28)
      at async esmock (file:///home/node-test/node_modules/esmock/src/esmock.js:20:25)
      at async makeSut (file:///home/node-test/index.test.js:8:10)
      at async Context.<anonymous> (file:///home/node-test/index.test.js:38:19)
```

Code samples: 

```js
// index.js
import fs from 'fs';
import got from 'got';

export const dImport = () => {
  const json = JSON.parse(
    fs.readFileSync(
      new URL('./index.json', import.meta.url)
    )
  )
  return json
}

export const getData = async () => {
  return got.get('https://pokeapi.co/api/v2/pokemon/ditto', { responseType: 'json' })
    .then(response => {
      console.log(response)
    })
}
```

```js
// index.test.js
import chai from 'chai'
import esmock from 'esmock'

const makeSut = async () => {
  return await esmock('./index.js', {
    fs: {
      readFileSync: () => {
        return JSON.stringify({ name: "node" })
      }
    },
    got: {
      get: async() => {
        return { data: 'ok' }
      }
    }
  })
}

describe('test index', () => {
  it('dImport should return correct value', async () => {
    const utils = await makeSut()
    assert.deepEqual(utils.dImport(), { name: "node" })
  })
})
```

## Current behavior
Facing `not a valid path: "got" ` when try to mock [got](https://www.npmjs.com/package/got)

## Expected behavior
esmock should mock `got`

## Environments
Ubuntu 18
Node 16.13.0
NPM 8.1.0

Thank you!

**Comment by iambumblehead** [comment]
@kdhttps thanks for opening this issue I'll take a look today. Maybe esmock needs to be updated with behaviour to resolve another es-type of export. I'll take a look soon

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/resolvewithplus/pull/14

This PR updates the package that will resolve the issue.

I hope you and others will continue to open issues. There are several complicated patterns of esm package.json exports and they aren't well defined. I'll update and add support for new patterns as they're encountered.

**Comment by iambumblehead** [comment]
@kdhttps the issue should be resolved with the latest version of esmock 1.7.4

feel free to close this discussion if the issue is resolved for you

**Comment by kdhttps** [comment]
thanks, much @iambumblehead :) but It is not mocking `got`, getting original API data in `got.get()` response instead of mock data.

```js
// index.js
import fs from 'fs';
import got from 'got';

export const dImport = () => {
  const json = JSON.parse(
    fs.readFileSync(
      new URL('./index.json', import.meta.url)
    )
  )
  return json
}

export const getData = async () => {
  try {
    const response = await got.get('https://pokeapi.co/api/v2/pokemon/ditto', { responseType: 'json' })
    return response.body
  } catch(e) {
    return e
  }
}
```

```js
// index.test.js
import chai from 'chai'
import esmock from 'esmock'
const assert = chai.assert

const makeSut = async () => {
  return await esmock('./index.js', {
    fs: {
      readFileSync: () => {
        return JSON.stringify({ name: "node" })
      }
    },
    got: {
      get: async(url, options) => {
        return { body : { data: "ok" } }
      }
    }
  })
}

describe('test index', () => {
  let utils

  before(async () => {
    utils = await makeSut()
  })

  after(async () => {
    esmock.purge(utils)
  })

  it('dImport should return correct value', async () => {
    assert.deepEqual(utils.dImport(), { name: "node" })
  })

  it('getData should return correct value', async () => {
    assert.deepEqual(await utils.getData(), { data: "ok" })
  })
})

```

am I missing something?

**Comment by iambumblehead** [comment]
@kdhttps "got" exports both default _and_ named exports. Explicitly define default this case ... try this,
```javascript
    got: {
      default: {
        get: async(url, options) => {
          return { body : { data: "ok" } }
        }
      }
    }
```

**Comment by kdhttps** [comment]
Cheers :tada: It is working. Thanks a lot again @iambumblehead . Closing this issue!
